language: c
compiler:
  - clang
  - gcc
sudo: required
script: cd libdockapp && autoreconf -i && ./configure && make install &&  cd .. && make
addons:
  apt:
    packages:
    - libxpm-dev
    - libasound2-dev
